version: "3"

services:
  api:
    container_name: contacts_ms
    restart: on-failure
    build: .
    volumes:
      - ./contacts_ms:/app
    ports:
      - "7777:7777"
    command: >
      sh -c "yarn start:dev"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: contacts_db
      MYSQL_USER: contacts
      MYSQL_PASSWORD: 2021
    ports:
      - "3308:3308"